### ISSUE TITLE
Requset image data.

### ISSUE THREAD

**Issue by ybx0000x0000xby** [lumen2018/dataset#1]
Dear auther:
  I write a latter to the E-mail address, but don't have a answer.
  在下写了一封电子邮件给作者您给的地址，但是至今没有得到回复。

**Comment by lumen2018** [comment]
您可以重发一封

**Comment by lumen2018** [comment]
抱歉，您可以重发一封，前段时间非常忙。

**Comment by ybx0000x0000xby** [comment]
收到了，非常感谢作者
